import {REGIONS,STYLES,clone,dateRange,recommendations,buildPlan,totals,timeline,clock,validatePlan,calendar} from './journey-core.mjs';
const $=id=>document.getElementById(id);
const form=$('journey-form'), result=$('journey-result'), status=$('journey-status');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const won=n=>Number(n).toLocaleString('ko-KR')+'원';
let plan=null,activeDay=0,dirty=false,history=[],future=[],printing=false,saving=false,owner=null,loaded=false,sharedDraft=false,authSettled=false;
const today=new Date();today.setDate(today.getDate()+7);const dayString=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
form.elements.start.value=dayString(today);form.elements.end.value=dayString(today);
function say(text){status.textContent=text;}
function readConfig(){return {region:form.elements.region.value,start:form.elements.start.value,end:form.elements.end.value,people:Number(form.elements.people.value),budget:Number(form.elements.budget.value),styles:[...form.querySelectorAll('[name=style]:checked')].map(el=>el.value),pace:form.elements.pace.value,transport:form.elements.transport.value,avoidWalk:form.elements.avoidWalk.checked,must:form.elements.must.value.trim()};}
function syncForm(){if(!plan)return;for(const key of ['region','start','end','people','budget','pace','transport','must'])if(form.elements[key])form.elements[key].value=plan.config[key]??'';form.elements.avoidWalk.checked=!!plan.config.avoidWalk;form.querySelectorAll('[name=style]').forEach(input=>input.checked=(plan.config.styles||[]).includes(input.value));recommend();}
function recommend(){const cfg=readConfig();const ranked=recommendations(cfg).slice(0,3);$('journey-recommendations').innerHTML=ranked.map(({region,reason},index)=>`<button type="button" class="journey-recommend" data-region="${region.id}" aria-pressed="${cfg.region===region.id}"><small>0${index+1} / ${esc(region.phrase)}</small><strong>${region.name}</strong><small>${esc(reason)}</small></button>`).join('');}
form.addEventListener('input',recommend);form.addEventListener('change',recommend);
$('journey-recommendations').addEventListener('click',event=>{const button=event.target.closest('[data-region]');if(!button)return;form.elements.region.value=button.dataset.region;recommend();say(`${REGIONS.find(r=>r.id===button.dataset.region).name}을 선택했습니다. 일정 만들기를 눌러주세요.`);});
function checkpoint(){if(plan)history.push(clone(plan));if(history.length>20)history.shift();future=[];}
function change(fn){checkpoint();fn();dirty=true;render();}
form.addEventListener('submit',event=>{event.preventDefault();try{const next=buildPlan(readConfig());if(plan&&dirty&&!window.confirm('아직 저장하지 않은 변경이 있습니다. 새 일정으로 바꿀까요?'))return;checkpoint();plan=next;activeDay=0;dirty=true;render();say('일정 초안을 만들었습니다. 장소·시간·비용을 편집한 뒤 저장하세요.');result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}catch(error){say(error.message);}});
const packing=['신분증과 결제수단','충전기와 보조배터리','날씨에 맞는 겉옷','예약·운영시간 확인','물과 개인 준비물'];
function dayHtml(day,index){const items=timeline(day,plan.config.transport);const end=items.at(-1)?.end||600;return `<section aria-label="${index+1}일차 ${day.date}"><div class="journey-day-top"><p>${day.date} · ${items.filter(i=>i.done).length}/${items.length} 완료</p><label class="journey-edit-only">하루 시작<input aria-label="하루 시작 시간" type="time" data-start-day="${index}" value="${day.start}" required></label></div>${end>18*60?'<p class="journey-warning">오후 6시 이후까지 이어지는 일정입니다. 장소를 줄이거나 체류시간을 조정해 보세요.</p>':''}<ol class="journey-timeline">${items.map((item,i)=>`<li class="journey-item ${item.done?'is-done':''}"><div><time>${clock(item.start)}</time><p class="journey-muted">${item.duration}분</p></div><div><h4>${esc(item.name)}</h4><p>${won(item.cost)} · 전체 인원 예상비용${i?' · 앞 일정 후 '+item.gap+'분 여유':''}</p>${item.note?`<p>${esc(item.note)}</p>`:''}<div class="journey-item-tools"><label class="journey-check"><input type="checkbox" data-done="${i}" data-day="${index}" ${item.done?'checked':''}>다녀옴</label><button type="button" data-edit="${i}" data-day="${index}">편집</button><details class="journey-item-more"><summary>더 보기</summary><div><button type="button" data-move="${i}" data-direction="-1" data-day="${index}" ${i===0?'disabled':''} aria-label="${esc(item.name)} 앞 순서로">앞으로</button><button type="button" data-move="${i}" data-direction="1" data-day="${index}" ${i===items.length-1?'disabled':''} aria-label="${esc(item.name)} 뒤 순서로">뒤로</button><button type="button" data-remove="${i}" data-day="${index}" aria-label="${esc(item.name)} 일정에서 삭제">삭제</button><a href="https://map.naver.com/p/search/${encodeURIComponent(REGIONS.find(r=>r.id===plan.region).name+' '+item.name)}" target="_blank" rel="noopener noreferrer">지도에서 찾기</a></div></details></div></div></li>`).join('')}</ol>${!items.length?'<p class="journey-muted">비어 있는 날입니다. 장소를 추가해 주세요.</p>':''}</section>`;}
function render(){if(!plan){result.innerHTML='<div class="journey-empty"><h3>아직 비어 있는 하루.</h3><p>여행 조건을 정하고 일정 만들기를 눌러주세요.</p><button class="journey-text" type="button" data-action="load">저장한 일정 불러오기</button></div>';return;}
 activeDay=Math.min(activeDay,plan.days.length-1);const sum=totals(plan),region=REGIONS.find(r=>r.id===plan.region);const state=window.MA_JOURNEY_STORAGE?.snapshot();
 result.innerHTML=`<div class="journey-plan-heading"><div><h3>${esc(plan.title)}</h3><p class="journey-muted">${plan.days[0].date} — ${plan.days.at(-1).date} · ${plan.config.people}명</p><p class="journey-muted">${dirty?'저장하지 않은 변경사항이 있습니다.':state?.owner==='guest'?'이 기기에 저장된 일정':'불러온 일정'}</p></div><a href="${region.source}" target="_blank" rel="noopener noreferrer" class="journey-text">${region.name} 관광 안내</a></div>
 <div class="journey-toolbar"><button class="journey-primary" data-action="save" ${saving?'disabled':''}>${saving?'저장 중…':'저장'}</button><button class="journey-button" data-action="share">공유</button><button class="journey-button" data-action="undo" ${history.length?'':'disabled'}>되돌리기</button><details class="journey-more"><summary>더 보기</summary><div class="journey-more-menu"><button class="journey-button" data-action="redo" ${future.length?'':'disabled'}>다시 적용</button><button class="journey-button" data-action="load">저장한 일정 불러오기</button><button class="journey-button" data-action="calendar">캘린더 내보내기</button><button class="journey-button" data-action="print">인쇄 · PDF</button><button class="journey-button" data-action="export">파일 저장</button><button class="journey-button" data-action="import">파일 열기</button></div></details></div>
 <div class="journey-day-tabs" role="group" aria-label="날짜 선택">${plan.days.map((day,i)=>`<button data-day-tab="${i}" aria-pressed="${i===activeDay}">${i+1}일차 <small>${day.date.slice(5).replace('-','.')}</small></button>`).join('')}</div>
 ${printing?plan.days.map(dayHtml).join(''):dayHtml(plan.days[activeDay],activeDay)}
 <div class="journey-toolbar journey-edit-only"><button class="journey-button" data-action="add" ${plan.days[activeDay].items.length>=12?'disabled':''}>장소 추가</button><button class="journey-text" data-action="rename">일정 이름 변경</button></div>
 <div class="journey-budget"><div class="journey-budget-heading"><span>예상 경비</span><strong>${won(sum.total)}</strong></div><progress max="${Math.max(plan.config.budget,1)}" value="${Math.min(sum.total,Math.max(plan.config.budget,1))}" aria-label="전체 예산 사용 비율"></progress><p class="journey-muted">1인 약 ${won(sum.perPerson)} · 장소·식사 ${won(sum.visits)}</p><p class="${sum.remaining<0?'journey-warning':'journey-muted'}">${sum.remaining<0?'예산보다 '+won(-sum.remaining)+' 높습니다.':'목표 예산까지 '+won(sum.remaining)+' 남았습니다.'}</p><details class="journey-cost-details"><summary>경비 조정</summary><div class="journey-fields"><label>숙박비 합계 · 원<input type="number" data-total="lodging" value="${plan.lodging}" min="0" max="100000000" step="1000"></label><label>교통비 합계 · 원<input type="number" data-total="transportCost" value="${plan.transportCost}" min="0" max="100000000" step="1000"></label></div><p class="journey-muted">숙박·교통·활동비 모두 계획용 추정치입니다. 교통비에는 출발지 왕복 비용을 직접 더해주세요.</p></details></div>
 <details class="journey-packing"><summary>출발 전, 챙길 것들</summary>${packing.map((name,i)=>`<label class="journey-check"><input type="checkbox" data-packed="${i}" ${(plan.checked||[]).includes(String(i))?'checked':''}>${name}</label>`).join('')}</details>`;
}
const editDialog=document.createElement('dialog');editDialog.className='journey-dialog';editDialog.setAttribute('aria-labelledby','journey-edit-title');document.body.append(editDialog);
function editItem(index,dayIndex){const item=index===null?{name:'',duration:60,cost:0,note:''}:plan.days[dayIndex].items[index];editDialog.innerHTML=`<form id="journey-edit-form"><div class="journey-dialog-head"><h3 id="journey-edit-title">${index===null?'장소 추가':'일정 편집'}</h3><button type="button" data-close aria-label="닫기">×</button></div><label>장소 이름<input name="name" required maxlength="80" value="${esc(item.name)}"></label><div class="journey-fields"><label>체류시간 · 분<input name="duration" type="number" min="10" max="480" step="5" required value="${item.duration}"></label><label>전체 인원 비용 · 원<input name="cost" type="number" min="0" max="100000000" required value="${item.cost}"></label></div><label>옮길 날짜<select name="day">${plan.days.map((day,i)=>`<option value="${i}" ${i===dayIndex?'selected':''}>${i+1}일차 · ${day.date}</option>`).join('')}</select></label><label>개인 메모<textarea name="note" maxlength="500" rows="3">${esc(item.note)}</textarea></label><button class="journey-primary" type="submit">반영하기</button></form>`;
 editDialog.querySelector('[data-close]').onclick=()=>editDialog.close();editDialog.querySelector('form').onsubmit=event=>{event.preventDefault();const f=event.currentTarget.elements,target=Number(f.day.value);if(target!==dayIndex&&plan.days[target].items.length>=12){say('선택한 날짜에는 최대 12개 장소까지 담을 수 있습니다.');return;}
 const next={id:index===null?crypto.randomUUID():item.id,name:f.name.value.trim(),duration:Number(f.duration.value),cost:Number(f.cost.value),category:item.category||'custom',note:f.note.value.trim(),done:!!item.done};if(!next.name)return;change(()=>{if(index!==null)plan.days[dayIndex].items.splice(index,1);if(index!==null&&target===dayIndex)plan.days[target].items.splice(index,0,next);else plan.days[target].items.push(next);activeDay=target;});editDialog.close();say('일정에 반영했습니다. 되돌리기로 취소할 수 있어요.');};editDialog.showModal();}
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function save(){if(!plan||saving)return;const bridge=window.MA_JOURNEY_STORAGE;if(!bridge){say('저장 기능에 연결하지 못했습니다. 파일 저장을 이용해 주세요.');return;}const next=clone(plan);saving=true;render();const success=await bridge.save(next);saving=false;if(success){dirty=JSON.stringify(plan)!==JSON.stringify(next);loaded=true;say(dirty?'이전 상태를 저장했습니다. 그 이후에 수정한 내용은 한 번 더 저장해 주세요.':'여행 계획을 저장했습니다.');}else say('저장하지 못했습니다. 편집한 일정은 화면에 유지됩니다. 파일로도 저장할 수 있습니다.');render();}
function load(force=false){const stored=window.MA_JOURNEY_STORAGE?.snapshot();if(!stored?.ready){say('계정 기록을 불러오는 중입니다. 잠시 후 다시 시도해 주세요.');return;}if(!stored.journey){if(force)say('저장된 여행 계획이 아직 없습니다.');return;}if(force&&dirty&&!window.confirm('저장한 일정을 불러오면 현재 변경사항이 대체됩니다. 계속할까요?'))return;try{plan=validatePlan(stored.journey);dirty=false;history=[];future=[];activeDay=0;loaded=true;syncForm();render();if(force)say('저장한 일정을 불러왔습니다.');}catch{say('저장된 일정 형식을 확인하지 못했습니다. 기존 기록은 변경하지 않았습니다.');}}
function storageChanged(){const state=window.MA_JOURNEY_STORAGE?.snapshot();if(!state)return;if(owner!==null&&owner!==state.owner&&!(sharedDraft&&!authSettled)){plan=null;dirty=false;history=[];future=[];loaded=false;editDialog.close();editDialog.innerHTML='';form.reset();form.elements.must.value='';form.elements.start.value=dayString(today);form.elements.end.value=dayString(today);recommend();say('계정이 변경되어 해당 계정의 기록으로 전환했습니다.');render();}owner=state.owner;if(state.authSettled)authSettled=true;if(!loaded&&!dirty&&state.ready){load();loaded=true;}}
window.addEventListener('ma:workspace-change',storageChanged);
function encode(value){const bytes=new TextEncoder().encode(JSON.stringify(value));let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function decode(text){if(text.length>30000)throw Error();return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(text.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))));}
function share(){const shared=clone(plan);shared.days.forEach(day=>day.items.forEach(item=>{item.note='';item.done=false;}));shared.checked=[];const url=new URL(location.pathname,location.origin);url.hash='trip='+encode(shared);if(url.href.length>12000){say('공유 링크가 너무 깁니다. 파일 저장으로 일정을 공유해 주세요.');return;}
 editDialog.innerHTML='<div class="journey-dialog-head"><h3 id="journey-edit-title">일정 공유</h3><button type="button" data-close aria-label="닫기">×</button></div><p class="journey-muted">링크를 받은 사람은 일정 이름·장소·날짜·인원·예산을 볼 수 있습니다. 개인 메모와 다녀옴 기록은 제외됩니다.</p><label>공유 링크<input readonly id="journey-share-url"></label><button class="journey-primary" id="journey-copy" type="button">링크 복사</button><p class="journey-status" id="journey-copy-status" role="status"></p>';
 $('journey-share-url').value=url.href;editDialog.querySelector('[data-close]').onclick=()=>editDialog.close();$('journey-copy').onclick=async()=>{try{await navigator.clipboard.writeText(url.href);$('journey-copy-status').textContent='복사했습니다.';}catch{$('journey-share-url').select();$('journey-copy-status').textContent='링크를 선택했습니다. 직접 복사해 주세요.';}};editDialog.showModal();}
const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.hidden=true;document.body.append(file);file.onchange=async()=>{const selected=file.files[0];if(!selected)return;try{if(selected.size>60000)throw Error('파일은 60KB 이하로 선택해 주세요.');const next=validatePlan(JSON.parse(await selected.text()));if(dirty&&!window.confirm('현재 변경사항을 파일의 일정으로 바꿀까요?'))return;checkpoint();plan=next;dirty=true;activeDay=0;syncForm();render();say('파일을 열었습니다. 내 기록으로 남기려면 저장하세요.');}catch(e){say(e.message||'일정 파일을 읽지 못했습니다.');}finally{file.value='';}};
result.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const data=button.dataset;
 if(data.dayTab!==undefined){activeDay=Number(data.dayTab);render();return;}if(data.edit!==undefined){editItem(Number(data.edit),Number(data.day));return;}
 if(data.move!==undefined){const i=Number(data.move),d=Number(data.day),to=i+Number(data.direction);change(()=>{const row=plan.days[d].items;[row[i],row[to]]=[row[to],row[i]];});say('순서를 변경하고 시간을 다시 계산했습니다.');return;}
 if(data.remove!==undefined){change(()=>plan.days[Number(data.day)].items.splice(Number(data.remove),1));say('장소를 뺐습니다. 되돌리기로 복원할 수 있어요.');return;}
 const actions={save,load:()=>load(true),add:()=>editItem(null,activeDay),undo:()=>{if(!history.length)return;future.push(clone(plan));plan=history.pop();dirty=true;syncForm();render();say('이전 상태로 되돌렸습니다.');},redo:()=>{if(!future.length)return;history.push(clone(plan));plan=future.pop();dirty=true;syncForm();render();},share,calendar:()=>download('ma-journey.ics',calendar(plan),'text/calendar;charset=utf-8'),export:()=>download('ma-journey.json',JSON.stringify(plan,null,2),'application/json'),import:()=>file.click(),print:()=>{printing=true;document.body.classList.add('print-journey');render();window.print();},rename:()=>{const name=window.prompt('일정 이름',plan.title);if(name?.trim())change(()=>plan.title=name.trim().slice(0,100));}};actions[data.action]?.();});
result.addEventListener('change',event=>{const target=event.target,data=target.dataset;
 if(data.done!==undefined){change(()=>plan.days[Number(data.day)].items[Number(data.done)].done=target.checked);}
 else if(data.packed!==undefined){change(()=>{const key=data.packed;plan.checked=target.checked?[...new Set([...(plan.checked||[]),key])]:(plan.checked||[]).filter(k=>k!==key);});const details=result.querySelector('.journey-packing');if(details)details.open=true;}
 else if(data.total){if(!target.value||!target.reportValidity())return;change(()=>plan[data.total]=Number(target.value));}
 else if(data.startDay!==undefined){if(!target.reportValidity())return;change(()=>plan.days[Number(data.startDay)].start=target.value);}
});
window.addEventListener('afterprint',()=>{printing=false;document.body.classList.remove('print-journey');render();});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
$('journey-load')?.addEventListener('click',()=>load(true));
recommend();
const fragment=new URLSearchParams(location.hash.slice(1));
if(fragment.has('trip')){try{plan=validatePlan(decode(fragment.get('trip')));sharedDraft=true;dirty=true;loaded=true;syncForm();render();say('공유받은 일정입니다. 수정한 뒤 내 기록으로 저장할 수 있어요.');}catch{say('공유 링크를 읽지 못했습니다. 새 링크나 일정 파일을 받아주세요.');}window.history.replaceState(null,'',location.pathname+location.search+'#journey');}
storageChanged();
